[WIP] Initial celery configuration
- Getting an error when running tests. See below for more info:

AttributeError: 'ChannelPromise' object has no attribute '__value__', is related to an issue within the kombu library, which is a messaging library used by Celery to communicate with message brokers like Redis or RabbitMQ. This specific error might arise due to an incompatibility between Celery, Kombu, and possibly other related packages in your environment.